[package]
name = "liquidation-protection"
version = "0.1.0"
edition = "2021"

[dependencies]
soroban-sdk = { workspace = true }

[lib]
crate-type = ["cdylib"]

[features]
testutils = ["soroban-sdk/testutils"]